import { Post } from '@/types/post';

export const POSTS: Post[] = [
  {
    _id: '1',
    text: "Let's build a fullstack WhatsApp clone with NEXT.JS 14 😍",
    img: '/posts/post1.png',
    user: {
      username: 'johndoe',
      profileImg: '/avatars/boy1.png',
      fullname: 'John Doe',
    },
    comments: [
      {
        _id: '1',
        text: 'Nice Tutorial',
        user: {
          username: 'janedoe',
          profileImg: '/avatars/girl1.png',
          fullname: 'Jane Doe',
        },
      },
    ],
    likes: ['6658s891', '6658s892', '6658s893', '6658s894'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: '2',
    text: 'How you guys doing? 😊',
    user: {
      username: 'johndoe',
      profileImg: '/avatars/boy2.png',
      fullname: 'John Doe',
    },
    comments: [
      {
        _id: '1',
        text: 'Nice Tutorial',
        user: {
          username: 'janedoe',
          profileImg: '/avatars/girl2.png',
          fullname: 'Jane Doe',
        },
      },
    ],
    likes: ['6658s891', '6658s892', '6658s893', '6658s894'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: '3',
    text: 'Astronaut in a room of drawers, generated by Midjourney. 🚀',
    img: '/posts/post2.png',
    user: {
      username: 'johndoe',
      profileImg: '/avatars/boy3.png',
      fullname: 'John Doe',
    },
    comments: [],
    likes: [
      '6658s891',
      '6658s892',
      '6658s893',
      '6658s894',
      '6658s895',
      '6658s896',
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: '4',
    text: "I'm learning GO this week. Any tips? 🤔",
    img: '/posts/post3.png',
    user: {
      username: 'johndoe',
      profileImg: '/avatars/boy3.png',
      fullname: 'John Doe',
    },
    comments: [
      {
        _id: '1',
        text: 'Nice Tutorial',
        user: {
          username: 'janedoe',
          profileImg: '/avatars/girl3.png',
          fullname: 'Jane Doe',
        },
      },
    ],
    likes: [
      '6658s891',
      '6658s892',
      '6658s893',
      '6658s894',
      '6658s895',
      '6658s896',
      '6658s897',
      '6658s898',
      '6658s899',
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const SUGGESTED_USERS = [
  {
    id: '1',
    fullname: 'Erma Dooley',
    username: 'erma_dooley',
    link: '/profile/erma_dooley',
    profileImg: 'https://i.pravatar.cc/150?img=1',
  },
  {
    id: '2',
    fullname: 'Naomi Vandervort',
    username: 'naomi_vandervort_95',
    link: '/profile/naomi_vandervort_95',
    profileImg: 'https://i.pravatar.cc/150?img=2',
  },
  {
    id: '3',
    fullname: 'Florence Casper',
    username: 'florcasper',
    link: '/profile/florcasper',
    profileImg: 'https://i.pravatar.cc/150?img=3',
  },
];
